UdemyMVC/ViewModels/Layout.cs
using System.Collections.Generic;

namespace UdemyMVC.ViewModels
{
    public class SidebarTag
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
        public string Slug { get; private set; }
        public int PostCount { get; private set; }

        public SidebarTag(int id, string name, string slug, int postCount)
        {
            Id = id;
            Name = name;
            Slug = slug;
            PostCount = postCount;
        }
    }

    public class LayoutSidebar
    {
        public bool IsLoggedIn { get; set; }
        public string Username { get; set; }
        public bool IsAdmin { get; set; }
        public IEnumerable<SidebarTag> Tags { get; set; }
    }
}

UdemyMVC/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHibernate.Linq;
using UdemyMVC.Models;
using UdemyMVC.ViewModels;

namespace UdemyMVC.Controllers
{
    public class LayoutController : Controller
    {
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            //var tags = Database.Session.Query<Tag>()
            return View( new LayoutSidebar
            {
                IsLoggedIn = Auth.User != null,
                Username = Auth.User != null ? Auth.User.Username : "",
                IsAdmin = User.IsInRole("admin"),
                Tags = Database.Session.Query<Tag>().Select(t=>new
                {
                    t.Id,
                    t.Name,
                    t.Slug,
                    PostCount = t.Posts.Count
                }).Where(t=>t.PostCount > 0)
                  .OrderByDescending(t=>t.PostCount)
                  .Select(tag=> new SidebarTag(tag.Id, tag.Name, tag.Slug, tag.PostCount)).ToList()

            });
        }
    }
}

UdemyMVC/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using System.Web.UI.WebControls
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Simple Blog</title>
    @Styles.Render("~/styles")
    
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>

    <div class="site-header">
        <header class="container">
            <h1 class="page-header">
                <a href="@Url.RouteUrl("Home")">Awesome Stuff</a>
                <small>a simple blog powered by ASP.net MVC</small>
            </h1>
        </header>



    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()
            </div>
            <div class="col-md-4 sidebar">
                @Html.Action("Sidebar", "Layout")
            </div>
        </div>
        <footer>
            &copy; @DateTime.UtcNow.Year
        </footer>
    </div>
















@Scripts.Render("~/scripts")
@RenderSection("Scripts", false)
</body>
</html>