UdemyMVC/Areas/Admin/ViewModels/Posts.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using UdemyMVC.Infrastructure;
using UdemyMVC.Models;

namespace UdemyMVC.Areas.Admin.ViewModels
{
    public class PostsIndex
    {
         public PagedData<Post> Posts { get; set; }
         
    }

    public class PostsForm
    {
        public PostsForm()
        {
            Tags = new List<TagCheckbox>();
        }
        public bool IsNew { get; set; }
        
        public int? PostId { get; set; }

        [Required, MaxLength(128)]
        public string Title { get; set; }
        
        [Required, DataType(DataType.MultilineText)]
        public string Content { get; set; }

        [Required, MaxLength(128)]
        public string Slug { get; set; }

        public IList<TagCheckbox> Tags { get; set; }
    }



    public class TagCheckbox
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public bool IsChecked { get; set; }

    }



















}

UdemyMVC/Models/Post.cs
using System;
using System.Collections.Generic;
using NHibernate.Mapping.ByCode.Conformist;
using NHibernate.Mapping.ByCode;

namespace UdemyMVC.Models
{
    public class Post
    {
        public Post()
        {
            Tags = new List<Tag>();
        }
        public virtual int Id { get; set; }
        public virtual User User { get; set; }

        public virtual string Title { get; set; }
        public virtual string Slug { get; set; }
        public virtual string Content { get; set; }

        public virtual DateTime CreatedAt { get; set; }
        public virtual DateTime? UpdatedAt { get; set; }
        public virtual DateTime? DeletedAt { get; set; }


        public virtual IList<Tag> Tags { get; set; } 
        public virtual bool IsDeleted
        {
            get { return DeletedAt != null; }
        }
    }




    public class PostMap : ClassMapping<Post>
    {
        public PostMap()
        {
            Table("posts");
            Id(x => x.Id, x => x.Generator(Generators.Identity));
            
            
            // Many to One association between Post and User
            ManyToOne(x=>x.User, x =>
            {
                x.Column("user_id");
                x.NotNullable(true);
            });


            Property(x=>x.Title, x=>x.NotNullable(true));
            Property(x=>x.Slug, x=>x.NotNullable(true));
            Property(x=>x.Content, x=>x.NotNullable(true));

            Property(x=>x.CreatedAt, x =>
            {
                x.Column("created_at");
                x.NotNullable(true);
            });
            Property(x=>x.UpdatedAt, x=>x.Column("updated_at"));
            Property(x=>x.DeletedAt, x=>x.Column("deleted_at"));


            // Many to Many Mapping is done with a Bag
            // Pivot table will be used; 1 posts_id, many tag_id & vice versa
            Bag(x => x.Tags, x =>
            {
                x.Key(y => y.Column("posts_id"));
                x.Table("posts_tags");

            }, x => x.ManyToMany(y => y.Column("tag_id")));
        }
    }







}

UdemyMVC/ViewModels/Posts.cs
using UdemyMVC.Infrastructure;
using UdemyMVC.Models;

namespace UdemyMVC.ViewModels
{
    public class PostsIndex
    {
        public PagedData<Post> Posts { get; set; }       
    }

    public class PostsShow
    {
        public Post Post { get; set; }

    }

   public class PostsTag
    {
        public Tag Tag { get; set; }
        public PagedData<Post> Posts { get; set; } 
    }
}

UdemyMVC/Areas/Admin/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using NHibernate.Linq;
using UdemyMVC.Areas.Admin.ViewModels;
using UdemyMVC.Infrastructure;
using UdemyMVC.Infrastructure.Extensions;
using UdemyMVC.Models;

namespace UdemyMVC.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [SelectedTab("posts")]
    public class PostsController : Controller
    {
        private const int PostsPerPage = 5;
        // GET: Admin/Posts
        public ActionResult Index(int page = 1)
        {
            var totalPostCount = Database.Session.Query<Post>().Count();
            var baseQuery = Database.Session.Query<Post>().OrderByDescending(c => c.CreatedAt);

            // Get a paginated list of PostIds.  This will make it so we don't have to make huge queries of data.
            // Just get the Ids first, then get the data for those Ids

            // Pagination
            var postIds = baseQuery
                .Skip((page - 1)*PostsPerPage)
                .Take(PostsPerPage)
                .Select(p => p.Id)
                .ToArray();


            // Data retrieval
            var currentPostPage = baseQuery
                .Where(p => postIds.Contains(p.Id))
                .FetchMany(f=>f.Tags)
                .Fetch(u=>u.User)
                .ToList();

            return View(new PostsIndex()
            {
                Posts = new PagedData<Post>(currentPostPage, totalPostCount, page, PostsPerPage)
            });
        }


        public ActionResult New()
        {
            return View("Form", new PostsForm()
            {
                IsNew = true,
                Tags = Database.Session.Query<Tag>().Select(tag => new TagCheckbox
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    IsChecked = false
                }).ToList()    
            });
        }

        public ActionResult Edit(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            
            return View("Form", new PostsForm()
            {
                IsNew = false,
                PostId = id,
                Content = post.Content,
                Slug =  post.Slug,
                Title = post.Title,
                Tags = Database.Session.Query<Tag>().Select(tag => new TagCheckbox
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    IsChecked = post.Tags.Contains(tag)
                }).ToList()
            });
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Form(PostsForm form)
        {

            form.IsNew = form.PostId == null;
            if (!ModelState.IsValid)
                return View(form);


            var selectedTags = ReconsileTags(form.Tags).ToList();

            Post post;
            if (form.IsNew)
            {
                post = new Post
                {
                    CreatedAt = DateTime.UtcNow,
                    User = Auth.User,
                };
                foreach (var tag in selectedTags)
                    post.Tags.Add(tag);
            }
            else
            {
                post = Database.Session.Load<Post>(form.PostId);
                if (post == null)
                    return HttpNotFound();

                post.UpdatedAt = DateTime.UtcNow;


                foreach (var toAdd in selectedTags.Where(t => !post.Tags.Contains(t)))
                {
                    post.Tags.Add(toAdd);
                }


                foreach (var toRemove in post.Tags.Where(t=> !selectedTags.Contains(t)).ToList())
                {
                    post.Tags.Remove(toRemove);
                }
            }

            post.Title = form.Title;
            post.Slug = form.Slug;
            post.Content = form.Content;





            Database.Session.SaveOrUpdate(post);

            return RedirectToAction("Index");
        }

        private IEnumerable<Tag> ReconsileTags(IEnumerable<TagCheckbox> tags)
        {
            foreach (var tag in tags.Where(t=>t.IsChecked))
            {
                if (tag.Id != null)
                {
                    yield return Database.Session.Load<Tag>(tag.Id);
                    continue;
                }
                var existingTag = Database.Session.Query<Tag>().FirstOrDefault(t => t.Name == tag.Name);
                if (existingTag != null)
                {
                    yield return existingTag;
                    continue;
                }

                var newTag = new Tag
                {
                    Name = tag.Name,
                    Slug = tag.Name.Slugify()
                };

                Database.Session.Save(newTag);
                yield return newTag;

            }
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Trash(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
                return HttpNotFound();

            post.DeletedAt = DateTime.UtcNow;
            Database.Session.Update(post);
            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
                return HttpNotFound();

            Database.Session.Delete(post);
            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Restore(int id)
        {
            var post = Database.Session.Load<Post>(id);
            if (post == null)
                return HttpNotFound();

            post.DeletedAt = null;
            Database.Session.Update(post);
            return RedirectToAction("Index");
        }



    } //class

}// namespace

UdemyMVC/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using NHibernate.Linq;
using UdemyMVC.Infrastructure;
using UdemyMVC.Models;
using UdemyMVC.ViewModels;

namespace UdemyMVC.Controllers
{
    public class PostsController : Controller
    {
        private const int PostsPerPage = 10;

        public ActionResult Index(int page = 1)
        {
            var baseQuery =
                Database.Session.Query<Post>().Where(x => x.DeletedAt == null).OrderByDescending(x => x.CreatedAt);

            var totalPostsCount = baseQuery.Count();
            var postIds = baseQuery.Skip((page - 1)*PostsPerPage).Take(PostsPerPage).Select(t => t.Id).ToArray();

            var posts = baseQuery.Where(p => postIds.Contains(p.Id)).FetchMany(t => t.Tags).Fetch(u => u.User).ToList();

            return View(new PostsIndex
            {
                Posts = new PagedData<Post>(posts, totalPostsCount, page, PostsPerPage)
            });
        }


        public ActionResult Tag(string idAndSlug, int page = 1)
        {
            var parts = SeparateIdAndSlug(idAndSlug);
            if (parts == null)
                return HttpNotFound();
            var tag = Database.Session.Load<Tag>(parts.Item1);

            if (tag == null)
                return HttpNotFound();


            if (!tag.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
                return RedirectToRoutePermanent("tag", new {id = parts.Item1, slug = tag.Slug});


            var totalPostCount = tag.Posts.Count();
            var postIds = tag.Posts
                .OrderByDescending(g=>g.CreatedAt)
                .Where(t=>t.DeletedAt == null)
                .Skip((page - 1)*PostsPerPage)
                .Take(PostsPerPage)
                .Select(t => t.Id)
                .ToArray();

           // var baseQuery =
            //      Database.Session.Query<Post>().Where(x => x.DeletedAt == null).OrderByDescending(x => x.CreatedAt);

            var posts =
                Database.Session.Query<Post>()
                    .OrderByDescending(t => t.CreatedAt)
                    .Where(t => postIds.Contains(t.Id))
                    .FetchMany(f => f.Tags)
                    .Fetch(u => u.User)
                    .ToList();



            return View(new PostsTag
            {
                Tag = tag,
                Posts = new PagedData<Post>(posts, totalPostCount, page, PostsPerPage)
            });



        }

        public ActionResult Show(string idAndSlug)
        {
            var parts = SeparateIdAndSlug(idAndSlug);
            if (parts == null)
                return HttpNotFound();
            var post = Database.Session.Load<Post>(parts.Item1);

            if (post == null || post.IsDeleted)
                return HttpNotFound();

            // if the ID is correct, but the Slug is not; Redirect to the correct id/slug combination
            // these weird routes and handling are for SEO purposes
            if (!post.Slug.Equals(parts.Item2, StringComparison.CurrentCultureIgnoreCase))
                return RedirectToRoutePermanent("Post", new {id = parts.Item1, slug = post.Slug});

            return View(new PostsShow
            {
                Post = post
            });
        }

        private Tuple<int, string> SeparateIdAndSlug(string idAndSlug)
        {
            var matches  = Regex.Match(idAndSlug, @"^(\d+)\-(.*)?$");
            if (!matches.Success)
                return null;

            var id = int.Parse(matches.Result("$1"));
            var slug = matches.Result("$2");


            var retTuple = Tuple.Create(id, slug);
            return retTuple;
        }
    }
}

UdemyMVC/Areas/Admin/Views/Posts/Form.cshtml
@using System.Web.Optimization
@model UdemyMVC.Areas.Admin.ViewModels.PostsForm
<h1>@(Model.IsNew ? "Create Post" : "Update Post")</h1>

@using (Html.BeginForm("Form", "Posts"))
{
    if (!Model.IsNew)
    {
        @Html.HiddenFor(f => f.PostId)
    }
    @Html.AntiForgeryToken()


    <div class="row">
        <div class="col-md-8">
            @Html.ValidationSummary()

            <div class="form-group">
                @Html.LabelFor(t => t.Title)
                
                @Html.TextBoxFor(f => f.Title, new {@class = "form-control"})
            </div>



            <div class="form-group">
                @Html.LabelFor(t => t.Slug)
                <!--  C# auto converts data_slug to data-slug  -->
                @Html.TextBoxFor(f => f.Slug, new {@class = "form-control", data_slug = "#Title" })
            </div>




            <div class="form-group">
                @Html.LabelFor(t => t.Content)
                @Html.TextAreaFor(f => f.Content, new { @class = "form-control" })
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Post Actions
                </div>
                <div class="panel-body">
                    <input type="submit" value="@(Model.IsNew ? "Publish Post" : "Update Post")" class="btn btn-success btn-sm"/>
                    <a href="@Url.Action("Index")">or cancel</a>
                </div>
            </div>


            <div class="panel panel-info">
                <div class="panel-heading">
                    Tags
                </div>
                <div class="panel-body post-tag-editor">
                    <label for="new-tag-name">Name Tag: </label>
                    <div class="input-group">
                        <input id="new-tag-name" type="text" class="new-tag-name form-control"/>
                        <span class="input-group-btn">
                            <button disabled class="btn btn-primary add-tag-button">Add</button>
                        </span>
                    </div>



                    <ul class="tag-select">
                        <li class="template">
                            <a href="#" class="name"></a>
                            <input type="hidden" class="name-input"/>
                            <input type="hidden" class="selected-input"/>

                        </li>


                        @for (var i = 0; i < Model.Tags.Count; i++)
                        {
                            var tag = Model.Tags[i];

                            <li data-tag-id="@tag.Id" class="@(tag.IsChecked ? "selected" : "")">
                                <a href="#">@tag.Name</a>

                                <input type="hidden" name="Tags[@(i)].Id" value="@tag.Id"/>
                                <input type="hidden" name="Tags[@(i)].Name" value="@tag.Name"/>
                                <input type="hidden" name="Tags[@(i)].IsChecked" value="@tag.IsChecked.ToString()" class="selected-input"/>
                            </li>
                        }
                    </ul>





                </div>
            </div>
        </div>
    </div>




}

@section Scripts
{
    @Scripts.Render("~/admin/post/scripts")


    <!-- ckeditor must be loaded manually, because it loads more scripts and is very particular, so it can't be bundled -->
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <!-- Content is the ID of the TextArea -->
    <script>
        CKEDITOR.replace("Content");
    </script>
}

UdemyMVC/Areas/Admin/Views/Posts/Index.cshtml
@model UdemyMVC.Areas.Admin.ViewModels.PostsIndex


<h1>Admin Posts</h1>


<div class="btn-toolbar">
    <div class="btn-group">
        <a href="@Url.Action("new")" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-plus"></i> Create Post</a>
    </div>

    <div class="btn-group pull-right">
        @if (Model.Posts.HasPreviousPage)
        {
            <a href="@Url.Action("Index", new {page = Model.Posts.PreviousPage})" class="btn btn-primary btn-sm">
                <i class="glyphicon glyphicon-chevron-left"></i>Previous Page
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default btn-disabled btn-sm">
                <i class="glyphicon glyphicon-chevron-left"></i> Previous Page
            </a>
        }



        @if (Model.Posts.HasNextPage)
        {
            <a href="@Url.Action("Index", new {page = Model.Posts.NextPage})" class="btn btn-primary btn-sm">
                Next Page <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
        else
        {
            <a href="#" class="btn btn-default btn-disabled btn-sm">
                Next Page <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
    </div>




</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Tags</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>

    </thead>
    <tbody>
    @foreach (var post in Model.Posts)
    {
        var cls = "";
        if (post.IsDeleted)
        {
            cls = "danger";
        }
        

        <tr class="@cls">
            <td>@post.Title</td>
            <td>@post.User.Username
            <td>@string.Join(", ", post.Tags.Select(t=>t.Name))</td>
            <td>@post.UpdatedAt</td>
            <td>
                <a href="@Url.Action("edit", new {post.Id})" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> edit</a>
                @if (!post.IsDeleted)
                {
                    <div class="btn-group btn-group-xs">
                        <a href="@Url.Action("trash", new { post.Id })" class="btn btn-danger" data-post="Are you sure you want to trash this post?">
                            <i class="glyphicon glyphicon-trash"></i> Trash
                        </a>
                        <a href="#" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" ><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="@Url.Action("Delete", new { post.Id })" class="" data-post="Are you sure you want to DELETE this post FOREVER?!?">
                                    <i class="glyphicon glyphicon-remove"></i> delete
                                </a>
                            </li>

                        </ul>
                    </div>
                }
                else
                {
                    <a href="@Url.Action("Restore", new { post.Id })" class="btn btn-xs btn-success" data-post="">
                        <i class="glyphicon glyicon-plus-sign"></i> restore
                    </a>
                }



            </td>
        </tr>
    }
    
    </tbody>

</table>